Modify ODGenerator.py and generator_driver

diff --git a/generator_driver b/generator_driver
--- a/generator_driver
+++ b/generator_driver
@@ -1,25 +1,57 @@
 #! /bin/bash
 
-
-# NOTE: I added LC_ALL=C because in some other locales, 'sort' does very
-#       strange things!  See:
-#   https://www.gnu.org/software/coreutils/faq/coreutils-faq.html#Sort-does-not-sort-in-normal-order_0021
-export LC_ALL=C
-
-
-TIME_LIMIT=10     # in seconds
+usage()
+{
+    echo "usage: generator_driver [[-f|--file filePath ] [-n|--numOfPairs NumberOfPairs] [-d|--debug] [-h|--help]]"
+}
 
 DOT_FILE_TESTER=ODGenerator
 
-if [[ ! -f ${DOT_FILE_TESTER}.py ]]
-then
-  echo "ERROR: ${DOT_FILE_TESTER}.py does not exist.  The grading script cannot continue." 1>&2
-  exit 1
-else
-  echo "Successfully find ${DOT_FILE_TESTER}.py in the current directory. Start running script"
+DIR=./POI/
+NUM=50
+DEBUG=
+
+while [ "$1" != "" ]; do
+    case $1 in
+        -f | --file )           shift
+                                DIR=$1
+                                ;;
+        -n | --numOfCases )     shift 
+                                NUM=$1
+                                ;;
+        -h | --help )           usage
+                                exit
+                                ;;
+        -d | --debug )          DEBUG=1
+                                ;;
+        * )                     usage
+                                exit 1
+    esac
+    shift
+done
+
+echo "filePath = $DIR"
+if echo "$NUM" | egrep -q '^\-?[0-9]+$'; then 
+    echo "Num of cases for each = $NUM"
+else 
+    echo "$NUM is not an integer"
+	exit 1
 fi
 
-DIR=./POI/
+
+if [ "$DEBUG" = "1" ]; then
+	echo "Debug mode is on"
+else
+	echo "Debug mode is off"
+fi
+
+if [[ ! -f ${DOT_FILE_TESTER}.py ]]
+then
+  echo "ERROR: ${DOT_FILE_TESTER}.py does not exist in the current directory. The generator_driver cannot continue." 1>&2
+  exit 1
+else
+  echo "Successfully find ${DOT_FILE_TESTER}.py in the current directory. Start to run the script"
+fi
 
 if [ ! -d ${DIR} ]; then
 	echo "No such directory: ${DIR}"
@@ -27,11 +59,11 @@ else
 	FILES=`ls ${DIR}`
 	
 	for X in ${FILES}; do
-		python2 ODGenerator.py  -f ${DIR}${X}
+		if [ "$DEBUG" = "1" ]; then
+			python2 ODGenerator.py  -f ${DIR}${X} -n ${NUM} -d
+		else
+			python2 ODGenerator.py  -f ${DIR}${X} -n ${NUM}
+		fi
 	done
 fi
-
-
-
-  
 
